### ISSUE TITLE
Example of how to use please?

### ISSUE THREAD

**Issue by ghost** [parnexcodes/mydramalist-api#1]
Can you please give me example on how to retrieve actor information?

Thank you

**Comment by parnexcodes** [comment]
I haven't added individual actors information. I'll add that soon.

**Comment by ghost** [comment]
Thank you. Also can you teach me how to use this? I don't really know how

**Comment by parnexcodes** [comment]
Just visit the endpoint eg : https://mydramalist-api-production.up.railway.app/api/shows/top
